### ISSUE TITLE
have you ever seen the project phichain?

### ISSUE THREAD

**Issue by ChickenPige0n** [nk980113/BPCE#1]
https://github.com/Ivan-1F/phichain

**Comment by nk980113** [comment]
Wow, didn't even expect to see this one.

Played with that one a bit, and here's some points:
- **Windowing design is impressive,** especially for people who used some softwares that have similar feature like Unity. I wanted to do similar design before, but I thought my coding skill didn't reach that level, so that idea got forgotten over time. Maybe someday I'll see how that's implemented.
- **UI design is neat.** I haven't used and don't want to use ImGUI yet, hope I can make UI as neat as that using only native Bevy UI.
- Editing experience looks pretty much like Unity, with RPE or other charting softwares (I believe) for notes editing.

But I think the current biggest problem of the Phigros Fanmade community is that everything is too stuck with RPE in a way. I promise that BPCE will give the community a brand new charting experience other than RPE.

Thanks for the recommendation, and stay tuned for BPCE!
